<<<<<<< HEAD
enum ScreenNames{
  SPLASH_SCREEN= 'Splash',
  ONBOARDING= 'Onboarding',
  HOME_SCREEN= 'HOME',
  Home= 'Home',
  Login= 'Login',
  Splash= 'Splash',
  Profile= 'Profile',
  BottomTab= 'BottomTab',
  Tutorial = 'Tutorial',
  Signin= 'SignIn',
  Signup= 'Signup',
  Details='Details',
  Search='Search',
  Searching='Searching',
  Setting='Setting',
  Add='Add',
  Notify='Notification',
  Save='Save',
  Category='Category',
  Otp='Otp',
  Post='Post',
  Scanner='Scanner',
  Scan='Scan',
  Chat='Chat',
  UserChat='UserChat',
  GroupChat = 'GroupChat',
  GroupChatting = 'GroupChatting',
  Stream = 'Stream',
  Voice = 'Voice',
  ScreenShare = 'ScreenShare',
  Role = 'Role',
  Promotion='Promotion',
  Training='Training',
  More='More',
  DealerSearch='DealerSearch',
  ProductDetailPage = 'ProductDetailPage',
  HondaCategory = 'HondaCategroy',
  GenratorProductListing = 'GenratorProductListing',
  newArrivals='newArrivals',
  Notification = 'Notification',
  Settings = 'Settings',
  ToggleNotifications = 'ToggleNotifications',
  FaqScreen = 'FaqScreen',
  PrivacePolicy = 'PrivacePolicy',
  WebViewScreen = 'WebViewScreen',
  NewHondaCategory = 'NewHondaCategory',
  ProfileScreen = 'ProfileScreen',
  RetailerScreen = 'RetailerScreen',
  RetailerFormScreen = 'RetailerFormScreen',
  YoutubeVideoScreen = 'YoutubeVideoScreen',
  ContactUs = 'ContactUs',
  EquipmentTraining = 'EquipmentTraining',
  DownLoadContentScreen = 'DownLoadContentScreen',
  CongratulationScreen = 'CongratulationScreen',
  CustomerSupportScreen = 'CustomerSupportScreen',
  modelCalculator = 'modelCalculator',
  engineScreenName= 'engineScreenName',
  hondaMarineScreen = 'hondaMarineScreen',
  commonFormScreen = 'commonFormScreen',
  hiPlusAgriMachinery = 'hiPlusAgriMachinery',
  VerifyEmail = 'VerifyEmail',
  promotionSeeMore = 'promotionSeeMore',
  commonDownloadScreen = 'commonDownloadScreen',
  yourProductsScreen = 'yourProductsScreen'
} ;
=======
enum ScreenNames {
  Splash = 'Splash',
  Tutorial = 'TutorialScreen',
  RoleSelect = 'SelectRole',
  Login = 'Login',
  VerifyOtp = 'VerifyOtp',
  Home = 'BottomNavigation',
  All = 'TobTabNavigation',
  Congratulation = 'Congratulation',
  ProductDetail='ProductDetailPage',
  honda_Category='Honda_Category',
  Generators='Generators',
  NewArrivals='NewArrivals',
  Notification='Notification',
  NewHondaCategory='NewHondaCategory',
  NewGenerators='NewGenerators',
  Tillers = 'Tillers',
  Profile = 'Profile',
  VerifyEmailOtp='VerifyEmailOtp',
  BottomNavigation = 'BottomNavigation',
}

>>>>>>> f681a5d601d3bc1b5efad13d01dee80dbb697625
export {ScreenNames};

