const Icons = {
  back: require('../assets/icons/back.png'),
  homeFocused: require('../assets/icons/homeSelected.png'),
  category:require('../assets/icons/category.png'),
  promotion:require('../assets/icons/promotion.png'),
  training:require('../assets/icons/training.png'),
  more:require('../assets/icons/more.png'),
  notification:require('../assets/icons/notification.png'),
  seeMore:require('../assets/icons/seeMore.png'),
  search:require('../assets/icons/search.png'),
  congratulation:require('../assets/icons/tick.png'),
  down:require('../assets/icons/down.png'),
  info:require('../assets/icons/info.png'),
  profile:require('../assets/icons/profile.png'),
  sort:require('../assets/icons/sort.png'),
  filter:require('../assets/icons/filter.png'),
  calendar: require('../assets/icons/calendar.png'),
  notificationBell: require('../assets/icons/notificationBell.png'),
  notificationOn: require('../assets/icons/notificationOn.png'),
  notificationOff: require('../assets/icons/notificationOff.png'),
  camera: require('../assets/icons/camera.png'),
  gallery: require('../assets/icons/gallery.png'),
  delete: require('../assets/icons/delete.png'),
  changeProfilePhoto: require('../assets/icons/changeProfilePhoto.png'),
  clock: require('../assets/icons/clock.png'),
  radioUnselected:require('../assets/icons/radioUnselected.png'),
  radioSelected:require('../assets/icons/radioSelected.png'),
};

const Images = {
  dashboardImage: require('../assets/images/dashboardImage.png'),
  splash: require('../assets/icons/splash.png'),
  logo:require('../assets/images/logo.png'),
  HIPlus:require('../assets/icons/hiPlus.png'),
  HIValuePlus: require('../assets/images/hiValuePlus.png'),
  bannerImage:require('../assets/images/banner.png'),
};
export {Images, Icons};
